cloudformation:
  rules:
    LAMBDA_001:
      enabled: true
    LAMBDA_002:
      enabled: true
    LAMBDA_003:
      enabled: true
      values:
        - tag1
        - tag2
    LAMBDA_004:
      enabled: true
      threshold: 0
    LAMBDA_005:
      enabled: true
      value: "ERROR"
    LAMBDA_006:
      enabled: true
    CW_001:
      enabled: true
      threshold: 14
    CW_002:
      enabled: true
    CW_003:
      enabled: false