AWSTemplateFormatVersion: "2010-09-09"
Description: "Example CloudFormation Template"

Parameters:
  EnvType:
    Type: String
    Default: "dev"
    Description: "The environment type."

Globals:
  Function:
    Runtime: python3.8
    Timeout: 300

Mappings:
  RegionMap:
    us-east-1:
      AMI: "ami-123456"
      HVM64: "ami-abcdef"
    us-west-1:
      AMI: "ami-789012"
      HVM64: "ami-ghijkl"

Resources:
  MyLogGroupp:
    Type: AWS::Logs::LogGroup
    Properties:

  MyLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: "MyLambda"
      Handler: "index.handler"
      Code:
        S3Bucket: "lambda-functions"
        S3Key: "function.zip"
      Role: "arn:aws:iam::123456789012:role/execution_role"
